<div class="container">
    <form class="formAdmInsert">
        <div class="row">
    <div class="col-md-7">
        <div class="form-group">
            <label>Nombre del Hito</label>
            <input type="text" name="inputName" class="form-control">
        </div>
    </div>
    <div class="col-md-7">
        <div class="form-group">
            <label>Proyecto</label>
            <select class="form-control" name="selectProducto">
                                                            <option value="0">Seleccione Un Proyecto</option>
                                                             <?php if($this->_getModulo)
                                                             {
                                                                foreach($this->_getModulo as $admMod)
                                                                {?>
                                                                    <option value="<?php echo $admMod->getId_producto() ?>"><?php echo $admMod->getNombre()?></option>  
                                                            
                                                           <?php
                                                           
                                                                }
                                                             }?>
                                                        </select>
          
        </div>
        <div class="col-md-7" >
                <a data-toggle="modal" class="btn btn-success" id="btnInsertModulo" onClick="Modulo.prototype.procesoEnviaForm('formAdmInsert', '<?php echo BASE_URL ?>modulo/insertModulo', 'btnInsertModulo', '<?php echo BASE_URL ?>modulo/abreAdmModulo')">
                    Guardar</a>
           </div>
    </div>
</div>
    </form>

</div>
