

<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#estadisticas">Estad&iacute;sticas de Usuarios</a></li>
    <li><a data-toggle="tab" href="#crearusuario">Crear Nuevo Usuario</a></li>
</ul>

<div class="tab-content">
  <div id="estadisticas" class="tab-pane fade in active">
      <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
                    <div class="page-header pull-left">
                        <div class="page-title">
                            Administración de Usuarios</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a href="sistema">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
                        <li class="hidden"><a href="#">Administración de Usuarios</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
                        <li class="active">Administración de Usuarios</li>
                    </ol>
                    <div class="clearfix">
                    </div>
                </div>
  <div class="page-content">
                    <div id="tab-general">
                        <div class="row mbl">
                            <div class="col-lg-12">
                                
                                            <div class="col-md-12">
                                                <div id="area-chart-spline" style="width: 100%; height: 300px; display: none;">
                                                </div>
                                            </div>
                                
                            </div>

                            <div class="col-lg-12">
                              
                                    
                              <div class="row">
                    <div class="col-lg-6">
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Line Chart</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body">
                                <div id="line-chart" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Bar Chart</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body">
                                <div id="bar-chart" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Area Chart</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body">
                                <div id="area-chart" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Pie Chart</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body">
                                <div id="pie-chart" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Line Chart - Spline</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body">
                                <div id="line-chart-spline" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Bar Chart - Stack</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body"><h4 class="block-heading">Bar Chart - Stack</h4>

                                <div id="bar-chart-stack" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Area Chart - Spline</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body">
                                <div id="Div1" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                        <div class="portlet box">
                            <div class="portlet-header">
                                <div class="caption">Percentiles Chart</div>
                                <div class="tools"><i class="fa fa-chevron-up"></i><i data-toggle="modal" data-target="#modal-config" class="fa fa-cog"></i><i class="fa fa-refresh"></i><i class="fa fa-times"></i></div>
                            </div>
                            <div class="portlet-body">
                                <div id="percentiles-chart" style="width: 100%; height:300px"></div>
                            </div>
                        </div>
                    </div>
                </div>
                 
                 


                              
                                </div>
                                
                            
                     
                            
                        </div>
                    </div>
                </div>
    
  </div>
  <div id="crearusuario" class="tab-pane fade">
    <div class="row">
        <div class="col-md-5">
            <h2 class="page-header">Datos Usuario</h2>
        </div>
         
    </div>
   <div class="row">
      <div class="panel panel-info">
        <div class="panel-heading">Datos Personales</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-7">
                    <div class="form-group">
                        <label>Usuario : </label>
                        <input type="text" name="txt_user" id="txt_user" class="form-control">
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="form-group">
                        <label>Correo : </label>
                        <input type="text" name="txt_correo" id="txt_correo" class="form-control">
                    </div>
                </div>
            </div>
        </div>
    </div> 
   </div>
  </div>
</div>
